### PR TITLE
Remove old git submodule

### PR DESCRIPTION
**Pull request by jspricke**
This was moved in a636c83 but the old directory was not deleted.

### CODE REVIEW

**Comment by phw** [comment]
Good catch, thanks a lot :)

**Comment by jspricke** [comment]
Could you also tag a new release? The current one breaks the F-Droid update scanner due to this.

**Comment by phw** [comment]
Oh, of course. I'll tag the release.

I won't build fresh apk though for now, as it brings no actual changes over 1.2.1 and I don't have my build environment quickly available. But I guess as F-Droid does build it itself it shouldn't matter.

**Comment by phw** [comment]
Ok, done

**Comment by phw** [comment]
@jspricke I did now do another proper release to fix layout issues on Android 10 in dark mode. Let me know if this all works for F-Droid now or if we still need some changes.

I'm also not really familiar anymore with how F-Droid updates. Is it fully automatic, or does one need to push updated infos to F-Droid repo for each update?

**Comment by jspricke** [comment]
> @jspricke I did now do another proper release to fix layout issues on Android 10 in dark mode. Let me know if this all works for F-Droid now or if we still need some changes.

Looks good to me, thx.

> I'm also not really familiar anymore with how F-Droid updates. Is it fully automatic, or does one need to push updated infos to F-Droid repo for each update?

We can fully automate it but currently it is still diesabeld: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.musicbrainz.picard.barcodescanner.yml#L42 and we need to wait for this fix: https://gitlab.com/fdroid/fdroidserver/-/merge_requests/955. I will enable the fully automate mode again once that is in.

**Comment by phw** [comment]
@jspricke I have pushed out more updates. The 1.3 release should be straight forward, but the 1.4 release brought the changes from #4 which changes quite a bit and bumps the min SDK version to 17. I hope this doesn't break anything for F-Droid. But it should simplify things also a bit because it gets rid of the submodule completely.

Is there anything I can do to get this updated on F-Droid? I must admit I'm still a bit confused how the proper update process is, it has been years since I looked at this stuff.

**Comment by jspricke** [comment]
The app was disabled due to a missing `PayPal_MPL-1.5.5.45.jar`:
https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.musicbrainz.picard.barcodescanner.yml#L42
we would need the source of it or a build flavor to build without it.

**Comment by phw** [comment]
@jspricke That jar is not required and should be removed from the build recipe then. The current version of the app should then build.

Might be that was indirectly required due to the external dependency on the modules of the old MusicBrainz app, but actually I never had this JAR anywhere for my builds. Don't know what happened ¯\_(ツ)_/¯

**Comment by jspricke** [comment]
Indeed 1.4.1 build find for me locally and I updated the metadata: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9410
It should become available through F-Droid in the coming days.

**Comment by phw** [comment]
@jspricke Thanks a lot for the support. Looks like it build successfully, looking forward to see this released :)

With the next releases things should become even better, especially the no longer required external barcode scanner app.

**Pull request merged**
