### PR TITLE
Replace AsyncTasks with coroutines

### PR DESCRIPTION
**Pull request by phw**
AsyncTaks are deprecated, replace with kotlin coroutines instead.

@akshaaatt Could you review this? Does this make sense that way or is there a better alternative?

### CODE REVIEW

**Comment by akshaaatt** [comment]
On it rn @phw

**Comment by akshaaatt** [comment]
First of all, congratulations on making such amazing changes to the app! Looks great 💯 

1) When using a suspend function, we remove the Throws annotation.
Coroutines should never call blocking functions since these block a thread and therefore stop any other coroutines to be executed on that thread. A better solution is to use suspending calls that just suspend the coroutine instead of blocking the thread.

2) We can use Retrofit for future use cases since it is a wrapper on OkHttp. That would ease things for us and we could document the codebase better.

**Comment by akshaaatt** [comment]
I want to make a few changes on top of this PR. I could do so by creating a new branch and making a separate PR. I think you can remove the Throws annotations and merge this PR. @phw :)

**Comment by phw** [comment]
>     1. When using a suspend function, we remove the Throws annotation.

Why the annotation? If I understand correctly Kotlin does not enforce the Throws annotation and it's optional. But does it make any functional difference if it is there? I was actually quite happy to see that an exception thrown on the thread, let's say here https://github.com/phw/PicardBarcodeScanner/blob/45409ee5ef9f294572b14a3d2eb32053af29bb5e/app/src/main/java/org/musicbrainz/picard/barcodescanner/activities/PerformSearchActivity.kt#L101 , would propagate properly.

To my understanding the catch block at https://github.com/phw/PicardBarcodeScanner/blob/45409ee5ef9f294572b14a3d2eb32053af29bb5e/app/src/main/java/org/musicbrainz/picard/barcodescanner/activities/PerformSearchActivity.kt#L80-L84 then runs on the main thread.

**Comment by phw** [comment]
Ok, I'll merge this and let you make an updated PR on top of this :) It seems to work in general and at least have the expected result of running the networking on a separate thread.

Retrofit looks interesting, especially as it also directly supports suspend functions. I originally thought about using the OkHttp callback functionality, but that code would have become messy, especially with the potentially multiple requests that sending all releases to Picard can cause.

Another thing to improve would be to actually switch the MB webservice to JSON and get rid of that awkward XML parsing. I think Retrofit can also help simplify this stuff.

**Comment by akshaaatt** [comment]
@phw Definitely! I think we can avoid the complexity, simply by introducing Retrofit. I will make some changes and we can further discuss them there.

**Pull request merged**
