### PR TITLE
Fix Certain Implementations & Dev Updates

### PR DESCRIPTION
**Pull request by akshaaatt**
We need to implement each class on its own and a base activity for implementing UI stuff does not help us much.

The menu functions are meant for us to override and allow us to define the implementation carefully for each menu item to enhance the user experience.

Fixes Issue:
- #24

### CODE REVIEW

**Comment by phw** [comment]
Thanks for the patch. But I don't really get the point.

First I would not remove the base class here. This pull request is moving a lot of duplicated code just down to the separate classes. If this would be the original code I would naturally refactor this to how it is currently.

The only real change I see is hiding the navigation item if your are already in preferences or about screen. But this could be more easily done with overriding `onCreateOptionsMenu`  like this:

```kotlin
override fun onCreateOptionsMenu(menu: Menu): Boolean {
    val result = super.onCreateOptionsMenu(menu)
    menu.findItem(R.id.action_settings).isVisible = false
    return result
}
```

Second I currently don't understand issue #24. Can you explain more detailed what the issue with back navigation is? I ran this code here and I did not notice any difference in navigation behavior. For me back navigation works the same in both current main branch and in this PR.

**Comment by akshaaatt** [comment]
Hi @phw!

Regarding the back button fixes, check these videos

https://user-images.githubusercontent.com/51470769/139541122-2411f581-e1fb-4c9c-b68f-7e628e9bb772.mp4


https://user-images.githubusercontent.com/51470769/139541130-0528a3dd-f057-4eb8-8b31-85541a614ad2.mp4

The first one is the fix I made vs the old issue.

The point about refactoring is that we do not want to showcase the already selected activity options in the menu, and to be able to do that, we would have to complicate the code in the BaseActivity to make cases by finding which activity is currently being used and so to decide what we want. This would work currently since the codebase is compact, but as we start adding more classes and activities, this base activity would get really complicated and hence I am of the opinion that we manage these cases for each activity separately. If you propose we do it in a better format, I am up for it!

**Comment by phw** [comment]
> The point about refactoring is that we do not want to showcase the already selected activity options in the menu, and to be able to do that, we would have to complicate the code in the BaseActivity to make cases by finding which activity is currently being used and so to decide what we want.

I fixed this in https://github.com/phw/PicardBarcodeScanner/commit/3776a2d6447518db81f99741764c7f780a06b6f3 by overriding the relevant method. No need to complicate code in the base class, in fact the base class ideally should not make any assumptions about behavior in the derived classes.

If we need specific behavior in activities we can solve this by overriding relevant methods like in this case. Also no activity is required to derive from the `BaseActivity` if that doesn't make sense. But currently the different activities share quite some code, and hence it is useful that they share this common code. Also we can refactor things once there is actually need for this. E.g. if there are a couple of new Activities and the current structure is not useful we can adapt.



> Regarding the back button fixes, check these videos

I see the issue, but I cannot reproduce. I assume the fix for this is the code at https://github.com/phw/PicardBarcodeScanner/pull/25/files#diff-445d39bfaea26df33654f3926a58beceae9d8c93a1dd782ff2f37db4d3869cbeR67-R70 ?

Could you adapt your PR for the fix and the smaller changes? Also please put those changes into separate commits, so that at least the bugfix is separate from the smaller code cleanup you did. That makes it easier to identify the actual change that solves the bug and to e.g. revert just specific changes if needed.

**Comment by akshaaatt** [comment]
@phw I see so your point is that we do use the BaseActivity and just override the menu option clicks in it. The item hiding can be done separately for every class. Okay I see that reasonable and that makes sense! I'll bring back that change.

**Pull request closed without merging**
